// Public key for Ed25519 license verification.
// Generated by: bun run generate-keypair
// To update: run generate-keypair, then paste the output here.
export const PUBLIC_KEY = 'MCowBQYDK2VwAyEAo4XhlSOLq96gOtM0dzi5aXj0laPmbT0oDAk+QLX6SNs='
