export { DuckDBManager } from './engine/manager'
export type { DuckDBManagerConfig } from './engine/manager'
export { ConnectionPool } from './engine/connection-pool'
export type { ConnectionPoolConfig } from './engine/connection-pool'
export { DataSourceRegistry } from './sources/registry'
export { FileSource } from './sources/file'
export { URLSource } from './sources/url'
export { SourceLoader } from './sources/loader'
export { QueryExecutor } from './query/executor'
export type { ConnectionHandle } from './query/executor'
export { QueryCache } from './query/cache'
export { FilterInjector } from './query/filter-injector'
export { SchemaInspector } from './schema/inspector'
export type { TableSchema, ColumnSchema } from './schema/inspector'
export { SchemaInference } from './schema/inference'
export * from './sources/types'
export * from './query/result'
export * from './query/filter-injector'
export * from './errors'
