import { DuckElement } from './base'
import { detectFilterType } from '@duck_ui/core'
import type { ColumnSchema } from '@duck_ui/core'

const filterBarCSS = `
  .filter-bar {
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
    align-items: flex-end;
    padding: 12px 16px;
    background: var(--duck-surface, #f9fafb);
    border: 1px solid var(--duck-border, #e5e7eb);
    border-radius: 8px;
  }
  .clear-btn {
    margin-left: auto;
    padding: 6px 14px;
    font-size: 13px;
    font-weight: 500;
    color: var(--duck-muted, #6b7280);
    background: var(--duck-bg, #ffffff);
    border: 1px solid var(--duck-border, #e5e7eb);
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.15s;
    line-height: 1.5;
  }
  .clear-btn:hover {
    background: var(--duck-hover, #f3f4f6);
    color: var(--duck-text, #374151);
  }
`

/**
 * <duck-filter-bar> — Container for filter elements with auto-detect and clear button.
 *
 * Usage:
 *   <!-- Auto-detect from table schema -->
 *   <duck-filter-bar auto="orders"></duck-filter-bar>
 *
 *   <!-- Manual filter placement -->
 *   <duck-filter-bar>
 *     <duck-select-filter column="status" source="orders" label="Status"></duck-select-filter>
 *     <duck-range-filter column="total" min="0" max="1000" label="Total"></duck-range-filter>
 *   </duck-filter-bar>
 */
export class DuckFilterBarElement extends DuckElement {
  static observedAttributes = ['auto', 'source']

  private bar!: HTMLDivElement
  private slotEl!: HTMLSlotElement
  private clearBtn!: HTMLButtonElement
  private autoGenerated = false

  render(): void {
    if (!this.bar) {
      this.applyStyles(filterBarCSS)
      this.bar = document.createElement('div')
      this.bar.className = 'filter-bar'

      this.slotEl = document.createElement('slot')
      this.bar.appendChild(this.slotEl)

      this.clearBtn = document.createElement('button')
      this.clearBtn.className = 'clear-btn'
      this.clearBtn.textContent = 'Clear filters'
      this.clearBtn.style.display = 'none'
      this.clearBtn.addEventListener('click', () => {
        this.getProvider()?.clearFilters()
      })
      this.bar.appendChild(this.clearBtn)

      this.shadow.appendChild(this.bar)
    }

    this.updateClearButton()
    this.autoDetect()
  }

  private updateClearButton(): void {
    const provider = this.getProvider()
    const hasActiveFilters = provider ? Object.values(provider.filters).some(
      (v) => v !== null && v !== undefined
    ) : false
    this.clearBtn.style.display = hasActiveFilters ? '' : 'none'
  }

  private async autoDetect(): Promise<void> {
    const auto = this.getAttribute('auto')
    if (!auto || this.autoGenerated) return

    const provider = this.getProvider()
    if (!provider?.ready) return

    try {
      const schema = await provider.duckUI.getSchema(auto)
      if (!schema) return

      const source = this.getAttribute('source') ?? auto

      for (const col of schema.columns) {
        const filterType = detectFilterType(col)

        if (filterType === 'select') {
          const el = document.createElement('duck-select-filter')
          el.setAttribute('column', col.name)
          el.setAttribute('source', source)
          el.setAttribute('label', col.name)
          this.appendChild(el)
        } else if (filterType === 'daterange') {
          const el = document.createElement('duck-date-filter')
          el.setAttribute('column', col.name)
          el.setAttribute('label', col.name)
          this.appendChild(el)
        }
      }

      this.autoGenerated = true
    } catch {
      // Silently fail auto-detect
    }
  }
}
